# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k0fIl6AsDlfP7jvP5XyYYPHWhimSvFwA
"""

import streamlit as st
import pandas as pd
import requests
import streamlit as st
import pandas as pd
import requests

# Función para obtener datos de una API
def obtener_datos_api(api_url):
    response = requests.get(api_url)
    if response.status_code == 200:
        data = response.json()
        return pd.DataFrame(data)
    else:
        st.error(f"Error al obtener los datos de la API: {response.status_code}")
        return None

# Título de la aplicación
st.title('Aplicación Web: Datos desde una API REST')

# API 1: JSONPlaceholder
st.header("Datos de JSONPlaceholder")
api_url_placeholder = 'https://jsonplaceholder.typicode.com/posts'
df_placeholder = obtener_datos_api(api_url_placeholder)

if df_placeholder is not None:
    st.write("Datos obtenidos de la API JSONPlaceholder:")
    st.write(df_placeholder.head())

# API 2: REST Countries
st.header("Datos de REST Countries")
api_url_countries = "https://restcountries.com/v3.1/all"
df_countries = obtener_datos_api(api_url_countries)



